### ISSUE TITLE
TestCafe issues on Lightning

### ISSUE THREAD

**Issue by ryanrudd** [neozenith/testcafe-sfdc-poc#1]
Hello, I found this repo from your comments in an issue on the TestCafe project.  You mentioned there sometime in March that after the latest version at that time (0.19 I believe) that you were no longer having issues.  I believe that we are having very similar issues (the base content for the lightning page loading, but dynamic layout content such as tabs and buttons are not rendering) when trying to setup a similar test POC.  We tried the dev branch that you mentioned as well as the latest version and are not having any luck.  Was there anything else that you had to do to work around that issue?  Is TestCafe still working for you in Lightning?  Any insight that you can provide would be greatly appreciated, thanks.

**Comment by neozenith** [comment]
Hi Ryan,

At the time the TestCafe team sorted the issue with the dev branch. 

So I could clone this repo, npm install and npm test. 

With Salesforce pushing out releases quarterly I dare say it is something in a subsequent release did Salesforce which broke it again. 

We needed it at the time to fairly POC a few options for automating UI testing in-house. 

We compared it to selenium and one other. 

We decided in the end that maintaining this in house was not a capability we want to support and went with a third party vendor claiming they could do it. 

My role was just to POC the in house implementations so I’m not sure who the vendor was and I’ve switched jobs since then. 

If you have a repo and clear instructions to replicate the issue I found the TestCafe team amazing with their support. 

In the end we canned it because of the SFDC component being out of our control and causing unplannable work. 

I hope that helps.
